Bellabeat Case Study
================
Elizabeth Gels
2023-03-03

# ABOUT THE COMPANY

Bellabeat is a high-tech manufacturer of health-focused products for
women. Collecting data on activity, sleep, stress, and reproductive
health has allowed Bellabeat to empower women with knowledge about their
own health and habits. Since it was founded in 2013, Bellabeat has grown
rapidly and quickly positioned itself as a tech-driven wellness company
for women.

By 2016, Bellabeat had opened offices around the world and launched
multiple products. Bellabeat products became available through a growing
number of online retailers in addition to their own e-commerce channel
on their website. The company has invested in traditional advertising
media, but focuses on digital marketing extensively.

Bellabeat products:

- Bellabeat app: It provides users with health data related to their
  activity, sleep, stress, menstrual cycle, and mindfulness habits. This
  data can help users better understand their current habits and make
  healthy decisions.

- Time: This wellness watch combines the timeless look of a classic
  timepiece with smart technology to track user activity, sleep, and
  stress. The Time watch connects to the Bellabeat app to provide you
  with insights into your daily wellness.

# ASK

## Business Task

Bellabeat is a successful small company, but they have the potential to
become a larger player in the global smart device market. Urška Sršen,
Bellabeat’s co-founder and Chief Creative Officer, believes that
analyzing smart device fitness data could help unlock new opportunities
for the company.

Working as a data analyst in the marketing analytics team, I will
analyze FitBit’s users data to gain insight into how consumers are using
their smart devices. Then, based on the insights discovered I will
provide high-level recommendations for Bellabeat’s marketing strategy.

# PREPARE

## Data Set

The FitBit Fitness Tracker Data is Public Domain and was made available
by users on Kaggle. Click here
([link](https://www.kaggle.com/datasets/arashnic/fitbit)) to view the
data set.

The data set contains information on FitBit fitness tracker usage,
collected from 33 eligible FitBit users who consented to the submission
of personal tracker data, including minute-level output for physical
activity, heart rate, and sleep monitoring.

These datasets were generated by respondents to a distributed survey via
Amazon Mechanical Turk between 04/12/2016 and 05/12/2016. Amazon
Mechanical Turk is part of Amazon.com, and they offer online
crowdsourcing tools for conducting research.

## Analytical Tool

The tool chosen for this analysis is R programming, used in the platform
of Rstudio Cloud.

# PROCESS AND ANALYSIS

## Loading R Packages

``` r
install.packages("tidyverse")
library(tidyverse)

install.packages("dplyr")
library(dplyr)

install.packages("lubridate")
library(lubridate)

install.packages("readr")
library(readr)

install.packages("skimr")
library(skimr)
```

## Daily Activity Data

Loading the daily_Activity file:

``` r
Daily_Activity <- read_csv("dailyActivity_merged.csv")
```

Looking at the structure of the table:

``` r
str(Daily_Activity)
```

    ## spc_tbl_ [940 × 15] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
    ##  $ Id                      : num [1:940] 1.5e+09 1.5e+09 1.5e+09 1.5e+09 1.5e+09 ...
    ##  $ ActivityDate            : chr [1:940] "4/12/2016" "4/13/2016" "4/14/2016" "4/15/2016" ...
    ##  $ TotalSteps              : num [1:940] 13162 10735 10460 9762 12669 ...
    ##  $ TotalDistance           : num [1:940] 8.5 6.97 6.74 6.28 8.16 ...
    ##  $ TrackerDistance         : num [1:940] 8.5 6.97 6.74 6.28 8.16 ...
    ##  $ LoggedActivitiesDistance: num [1:940] 0 0 0 0 0 0 0 0 0 0 ...
    ##  $ VeryActiveDistance      : num [1:940] 1.88 1.57 2.44 2.14 2.71 ...
    ##  $ ModeratelyActiveDistance: num [1:940] 0.55 0.69 0.4 1.26 0.41 ...
    ##  $ LightActiveDistance     : num [1:940] 6.06 4.71 3.91 2.83 5.04 ...
    ##  $ SedentaryActiveDistance : num [1:940] 0 0 0 0 0 0 0 0 0 0 ...
    ##  $ VeryActiveMinutes       : num [1:940] 25 21 30 29 36 38 42 50 28 19 ...
    ##  $ FairlyActiveMinutes     : num [1:940] 13 19 11 34 10 20 16 31 12 8 ...
    ##  $ LightlyActiveMinutes    : num [1:940] 328 217 181 209 221 164 233 264 205 211 ...
    ##  $ SedentaryMinutes        : num [1:940] 728 776 1218 726 773 ...
    ##  $ Calories                : num [1:940] 1985 1797 1776 1745 1863 ...
    ##  - attr(*, "spec")=
    ##   .. cols(
    ##   ..   Id = col_double(),
    ##   ..   ActivityDate = col_character(),
    ##   ..   TotalSteps = col_double(),
    ##   ..   TotalDistance = col_double(),
    ##   ..   TrackerDistance = col_double(),
    ##   ..   LoggedActivitiesDistance = col_double(),
    ##   ..   VeryActiveDistance = col_double(),
    ##   ..   ModeratelyActiveDistance = col_double(),
    ##   ..   LightActiveDistance = col_double(),
    ##   ..   SedentaryActiveDistance = col_double(),
    ##   ..   VeryActiveMinutes = col_double(),
    ##   ..   FairlyActiveMinutes = col_double(),
    ##   ..   LightlyActiveMinutes = col_double(),
    ##   ..   SedentaryMinutes = col_double(),
    ##   ..   Calories = col_double()
    ##   .. )
    ##  - attr(*, "problems")=<externalptr>

The variables are: Id (User’s Unique Identifier), Activity Date (in
MM/DD/YYYY format), Total Steps and Calories burned.

FitBit tracks Minutes and Distance (Km) by Intensity levels: Sedentary,
Lightly Active, Fairly (Moderately) Active and Very Active. However,
there’s no proper or technical definitions for these levels. Based on
information by the Harvard T.H. Chan, School of Public Health
[link](https://www.hsph.harvard.edu/nutritionsource/staying-active/), we
assumed that the intensities used in this sample correspond to the
following examples:

- Sedentary: Sitting, reclining, or lying down.
- Light intensity: Walking at a leisurely pace or standing in line at
  the store.
- Moderate (Fairly) intensity: Walking briskly, vacuuming, or raking
  leaves.
- Vigorous (Very Active): Walking very quickly, running, taking an
  aerobics class, or shoveling snow.

No duplicates were found:

``` r
nrow(Daily_Activity[duplicated(Daily_Activity), ])
```

    ## [1] 0

Changing the data type for variable ActivityDate (from character to
date) by creating a new column:

``` r
Daily_Activity$ActivityDate_New <- mdy(Daily_Activity$ActivityDate)
```

By counting unique values, we confirm we have 33 unique users, 31 days
and 940 observations:

``` r
n_distinct(Daily_Activity$Id)
```

    ## [1] 33

``` r
n_distinct(Daily_Activity$ActivityDate_New)
```

    ## [1] 31

``` r
nrow(Daily_Activity)
```

    ## [1] 940

Looking at data stats:

``` r
Daily_Activity %>%  
  summary()
```

    ##        Id            ActivityDate         TotalSteps    TotalDistance   
    ##  Min.   :1.504e+09   Length:940         Min.   :    0   Min.   : 0.000  
    ##  1st Qu.:2.320e+09   Class :character   1st Qu.: 3790   1st Qu.: 2.620  
    ##  Median :4.445e+09   Mode  :character   Median : 7406   Median : 5.245  
    ##  Mean   :4.855e+09                      Mean   : 7638   Mean   : 5.490  
    ##  3rd Qu.:6.962e+09                      3rd Qu.:10727   3rd Qu.: 7.713  
    ##  Max.   :8.878e+09                      Max.   :36019   Max.   :28.030  
    ##  TrackerDistance  LoggedActivitiesDistance VeryActiveDistance
    ##  Min.   : 0.000   Min.   :0.0000           Min.   : 0.000    
    ##  1st Qu.: 2.620   1st Qu.:0.0000           1st Qu.: 0.000    
    ##  Median : 5.245   Median :0.0000           Median : 0.210    
    ##  Mean   : 5.475   Mean   :0.1082           Mean   : 1.503    
    ##  3rd Qu.: 7.710   3rd Qu.:0.0000           3rd Qu.: 2.053    
    ##  Max.   :28.030   Max.   :4.9421           Max.   :21.920    
    ##  ModeratelyActiveDistance LightActiveDistance SedentaryActiveDistance
    ##  Min.   :0.0000           Min.   : 0.000      Min.   :0.000000       
    ##  1st Qu.:0.0000           1st Qu.: 1.945      1st Qu.:0.000000       
    ##  Median :0.2400           Median : 3.365      Median :0.000000       
    ##  Mean   :0.5675           Mean   : 3.341      Mean   :0.001606       
    ##  3rd Qu.:0.8000           3rd Qu.: 4.782      3rd Qu.:0.000000       
    ##  Max.   :6.4800           Max.   :10.710      Max.   :0.110000       
    ##  VeryActiveMinutes FairlyActiveMinutes LightlyActiveMinutes SedentaryMinutes
    ##  Min.   :  0.00    Min.   :  0.00      Min.   :  0.0        Min.   :   0.0  
    ##  1st Qu.:  0.00    1st Qu.:  0.00      1st Qu.:127.0        1st Qu.: 729.8  
    ##  Median :  4.00    Median :  6.00      Median :199.0        Median :1057.5  
    ##  Mean   : 21.16    Mean   : 13.56      Mean   :192.8        Mean   : 991.2  
    ##  3rd Qu.: 32.00    3rd Qu.: 19.00      3rd Qu.:264.0        3rd Qu.:1229.5  
    ##  Max.   :210.00    Max.   :143.00      Max.   :518.0        Max.   :1440.0  
    ##     Calories    ActivityDate_New    
    ##  Min.   :   0   Min.   :2016-04-12  
    ##  1st Qu.:1828   1st Qu.:2016-04-19  
    ##  Median :2134   Median :2016-04-26  
    ##  Mean   :2304   Mean   :2016-04-26  
    ##  3rd Qu.:2793   3rd Qu.:2016-05-04  
    ##  Max.   :4900   Max.   :2016-05-12

Transforming the data by creating a new table
Daily_Activity_AddedColumns. We add the following new columns to
Daily_Activity: Sum of total minutes, minutes to hours conversion,
percentages of time by activity and days of the week.

``` r
Daily_Activity_AddedColumns <- Daily_Activity %>%
  mutate(totalminutes=(SedentaryMinutes + LightlyActiveMinutes + FairlyActiveMinutes + VeryActiveMinutes),
         hoursaday=(totalminutes/60), Percentageused=((hoursaday/24)*100), 
         veryactiveminutesp=((VeryActiveMinutes/totalminutes)*100),
         fairlyactiveminutesp=((FairlyActiveMinutes/totalminutes)*100),
         lightlyactiveminutesp=((LightlyActiveMinutes/totalminutes)*100),
         sedentaryminutesp=((SedentaryMinutes/totalminutes)*100),
         dayofweek=weekdays(ActivityDate_New))
```

### Minutes of Daily Activity

Total Minutes stats:

Median: 1,440.0 minutes (24 hours)  
Mean: 1,218.8 minutes (20.3 hours)

From the start, these stats seem high when considering that sleep hours
haven’t been accounted for.

Transforming the data to calculate averages for Minutes and Distance.

``` r
Daily_Activity_AddedColumns2 <- Daily_Activity_AddedColumns %>%
  group_by(dayofweek) %>%
  summarise(avgveryactivemin=mean(VeryActiveMinutes),
         avgfairlyactivemin=mean(FairlyActiveMinutes),
         avglightlyactivemin=mean(LightlyActiveMinutes),
         avgsedentarymin=mean(SedentaryMinutes),
         avgveryactivedis=mean(VeryActiveDistance),
         avgfairlyactivedis=mean(ModeratelyActiveDistance),
         avglightlyactivedis=mean(LightActiveDistance),
         avgsedentarydis=mean(SedentaryActiveDistance))
```

Pivoting previous table:

``` r
dtav <- gather(Daily_Activity_AddedColumns2, key="typeofActivity", value="Average", 2:9)
```

Creating graph:

``` r
dtav$dayofweek <- ordered(dtav$dayofweek, levels=c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", 
     "Saturday", "Sunday"))

ggplot(dtav[1:28, ], aes(x=typeofActivity, y=Average, fill=typeofActivity)) + 
    geom_bar(stat="identity") +
    labs(x="", y="Average Minutes", title="Average Minutes by Activity Type and Day of the Week") +
    geom_text(aes(label=round(Average)), position=position_dodge(width=0.9), vjust=-0.25, size=2.5) +
    scale_x_discrete(labels=c("Fairly", "Lightly", "Sedentary", "Very Active")) + 
    theme(axis.text.x = element_text(angle=45), legend.position="right") +
    scale_fill_manual(values=c("#E69F00", "#458B00", "#56B4E9", "#EE3B3B"), name="",
    labels=c("Fairly", "Lightly", "Sedentary", "Very Active")) + 
    facet_wrap(~dayofweek) 
```

![](Bellabeat-Copy-From-Kaggle_files/figure-gfm/unnamed-chunk-11-1.png)<!-- -->
![unnamed-chunk-11-1](https://github.com/elgels/Bellabeat-Case-Study/assets/131495309/5647b9d4-35c9-4cbe-a407-a575ec74064b)

There is small variation in the averages of time per activity across the
days of the week.

- Average of Lightly Active Minutes slightly increase on Fridays and
  Saturdays

- Average of Fairly Active Minutes slightly increase on Saturdays and
  Sundays.

- Average of Very Active Minutes slightly increase on Mondays and
  Tuesdays.

The pattern seems to indicate that people tend to exercise vigorously
(Very Active) during the first days of the week (Monday, Tuesdays,
Wednesday), and have more Light and Fairly activity minutes during the
weekend. This could be related to weekend activities such as doing
groceries or cleaning.

### Sedentary Minutes

As a group, users spent an average of 80% of their daily time in
sedentary activities. This percentage seems large, therefore we look
into this variable a little closer:

- Mean: 991.2 minutes (15.5 hours)
- Median: 1,057.5 minutes (17.6 hours)

To produce a graph, we create a data frame that shows users’ average
percentage of time per activity.

``` r
category <- c("average_veryactive", "average_fairlyactive", "average_lightlyactive", "average_sedentary") 
percentages <- c(1.84, 1.20, 16.98, 79.98)

summary_average_minutes <- data.frame(category, percentages)
```

``` r
ggplot(summary_average_minutes, aes(x=" ", y=percentages, fill=category)) + 
    geom_bar(stat="identity", width=1) + coord_polar(theta = "y") +
    geom_text(aes(label = scales::percent(percentages/100)), position = position_stack(vjust = 0.4),
    size = 3, check_overlap= TRUE)  +
    labs(x = " ", y = " ", title = "Average Percentage of Daily Time by Activity Type") + 
    scale_fill_discrete(name = "Activity Type", 
    labels = c("Fairly Active", "Lighlty Active", "Sedentary", "Very Active")) +
    theme_void()
```

![](Bellabeat-Copy-From-Kaggle_files/figure-gfm/unnamed-chunk-13-1.png)<!-- -->
![unnamed-chunk-13-1](https://github.com/elgels/Bellabeat-Case-Study/assets/131495309/2653f3c2-f783-4c69-8751-8fd128dcaafa)

While in average, 80% of total minutes was spent as Sedentary, 17% was
considered Lightly Active and roughly 3% was both Fairly and Very Active
time.

``` r
Daily_Activity_AddedColumnssm <- Daily_Activity_AddedColumns %>% group_by(Id )%>% 
    summarise(SedentaryHoursperId=(mean(SedentaryMinutes))/60)

ggplot(Daily_Activity_AddedColumnssm, aes(x=Id, y=SedentaryHoursperId)) + geom_point() +
    labs(x="User Id", y="Sedentary Hours per Day", title="Sedentary Hours by User") 
```

![](Bellabeat-Copy-From-Kaggle_files/figure-gfm/unnamed-chunk-14-1.png)<!-- -->
![unnamed-chunk-14-1](https://github.com/elgels/Bellabeat-Case-Study/assets/131495309/0c5f1fd1-3057-44c7-bc46-5945b7dcb4ac)

When plotting Sedentary hours per user Id, we seem to find two groups:

- 14 users (42%) have Sedentary times between 11 and 15 hours.
- 19 users (58%) have Sedentary times between 17 and 22 hours.

Studies suggest that typical adult Sedentary time is around. 9.5 hours a
day. Considering that one day has 24 hours, it seems that Sedentary
Minutes were largely overestimated when collecting the data.

### Distance (Km) of Daily Activity

The average person walks roughly 1.5 to 2 miles. Looking at the mean for
total Distance (3.41 miles), most users seem to be doing better than
average but still below the recommended distance of 5 miles (10,000
steps) a day.

- Median: 5.245 km (3.26 miles)
- Mean: 5.490 km (3.41 miles)

Users in average recorded 71% of their total daily distance as Light
Distance, 9% was Moderately (Fairly) Distance and 19% was Very Active
Distance. Just as with Sedentary Minutes being almost 80% of the total
time, for the most part people tend to be sedentary, and to walk mostly
for light activities during the day.

``` r
ggplot(dtav[29:56, ], aes(x=typeofActivity, y=Average, fill=typeofActivity)) + geom_bar(stat="identity") +
    labs(x="", y="Average Distance (Km)", title="Average Distance by Activity Type and Day of the Week") +
    geom_text(aes(label=round(Average, 2)), position=position_dodge(width=0.9), vjust=-0.25, size=2.5) +
    scale_x_discrete(labels=c("Fairly", "Lightly", "Sedentary", "Very Active")) + 
    theme(axis.text.x = element_text(angle=45), legend.position="right") +
    scale_fill_manual(values=c("#E69F00", "#458B00", "#56B4E9", "#EE3B3B"), name="",
    labels=c("Fairly Active", "Lightly Active", "Sedentary", "Very Active")) + 
    facet_wrap(~dayofweek) 
```

![](Bellabeat-Copy-From-Kaggle_files/figure-gfm/unnamed-chunk-15-1.png)<!-- -->
![unnamed-chunk-15-1](https://github.com/elgels/Bellabeat-Case-Study/assets/131495309/fc955699-a7a8-4614-91c9-b2e902cf1d4f)

Just as with time, there is small variation in the averages of distance
per activity across the days of the week.

- Average of Light Active Distance peaks on Saturday.

- Average of Fairly Active Distance peaks on Saturday and Sunday.

- Average of Very Active Distance peaks on Tuesday and Wednesday.

This pattern is consistent with what we found when looking at Minutes of
Activity per day of the week. Very Active Distance is related to the
first days of the week, while Fair and Light Active Distance tend to
happen during weekends.

### Steps

Most respondents (26 users, 79% of total) are below the recommended
number of 10,000 steps a day.

- Median: 7,406 steps (3.51 miles)
- Mean: 7,638 steps (3.62 miles)

``` r
ggplot(Daily_Activity_AddedColumns) +
  aes(x = "", y = TotalSteps) +
  xlab(" ") +
  ylab("Steps") +  
  ggtitle("Total Steps Box Plot") +
  theme_minimal() +
  geom_boxplot(fill = "#0c4c8a") 
```

![](Bellabeat-Copy-From-Kaggle_files/figure-gfm/unnamed-chunk-16-1.png)<!-- -->
![unnamed-chunk-16-1](https://github.com/elgels/Bellabeat-Case-Study/assets/131495309/4bca966f-53f0-4134-b89e-3c8d5c9f6c10)

``` r
Daily_Activity_AddedColumns3 <- Daily_Activity_AddedColumns %>%
  group_by(dayofweek) %>%
  summarise(avgsteps=mean(TotalSteps))
```

``` r
Daily_Activity_AddedColumns3$dayofweek <- ordered(Daily_Activity_AddedColumns3$dayofweek, 
    levels=c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"))

ggplot(data=Daily_Activity_AddedColumns3, aes(x=dayofweek, y=avgsteps)) + labs(x="Day of the Week", 
    y="Average Steps per Day", title="Average Steps by Day of the Week") + 
    geom_bar(fill="#0c4c8a", stat="identity")
```

![](Bellabeat-Copy-From-Kaggle_files/figure-gfm/unnamed-chunk-18-1.png)<!-- -->
![unnamed-chunk-18-1](https://github.com/elgels/Bellabeat-Case-Study/assets/131495309/169895a0-c6b6-4cc3-a1ba-ad07e4658d55)

- Surprisingly the most Steps are taken on Saturdays, this might be
  related to a slight increase in Lightly and Fairly Active Distances
  for that day.

- Tuesday has the second highest number of Steps taken. This is
  consistent with a slight increase on Very Active Distance for that
  day.

- Sunday has the least amount of Steps taken which might reflect that
  Lightly Active Distance is the lowest on this day as well.

As notice before this pattern seems to indicate that Steps on Tuesdays
are linked to more intense exercise, while weekends seemed to be linked
to lighter intensity activities. Most people tend to do errands,
groceries or cleaning during weekends.

### Calories

The recommended daily calorie intake is around 2,500 calories for men
and 2,000 calories for women. In average, more than half of the users in
this sample fall within a 1,800 to 2,700 calorie range.

- Median: 2,134 calories
- Mean: 2,304 calories

``` r
ggplot(Daily_Activity_AddedColumns) +
  aes(x = "", y = Calories) +
  xlab(" ") +
  ylab("Calories") +  
  ggtitle("Calories Box Plot") +
  theme_minimal() +
  geom_boxplot(fill = "#0c4c8a") 
```

![](Bellabeat-Copy-From-Kaggle_files/figure-gfm/unnamed-chunk-19-1.png)<!-- -->
![unnamed-chunk-19-1](https://github.com/elgels/Bellabeat-Case-Study/assets/131495309/97e32bf9-4160-4d5f-8a4e-d38eea600d86)

## Sleep Data

Loading the sleepDay file:

``` r
Sleep_Day <- read_csv("sleepDay_merged.csv")
```

    ## Rows: 413 Columns: 5
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): SleepDay
    ## dbl (4): Id, TotalSleepRecords, TotalMinutesAsleep, TotalTimeInBed
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Only 24 participants recorded sleep hours:

``` r
n_distinct(Sleep_Day$Id)
```

    ## [1] 24

``` r
nrow(Sleep_Day)
```

    ## [1] 413

Looking at data stats:

``` r
  Sleep_Day %>%
  summary()
```

    ##        Id              SleepDay         TotalSleepRecords TotalMinutesAsleep
    ##  Min.   :1.504e+09   Length:413         Min.   :1.000     Min.   : 58.0     
    ##  1st Qu.:3.977e+09   Class :character   1st Qu.:1.000     1st Qu.:361.0     
    ##  Median :4.703e+09   Mode  :character   Median :1.000     Median :433.0     
    ##  Mean   :5.001e+09                      Mean   :1.119     Mean   :419.5     
    ##  3rd Qu.:6.962e+09                      3rd Qu.:1.000     3rd Qu.:490.0     
    ##  Max.   :8.792e+09                      Max.   :3.000     Max.   :796.0     
    ##  TotalTimeInBed 
    ##  Min.   : 61.0  
    ##  1st Qu.:403.0  
    ##  Median :463.0  
    ##  Mean   :458.6  
    ##  3rd Qu.:526.0  
    ##  Max.   :961.0

Changing data type for variable Sleepday (from character to date) by
creating a new column:

``` r
Sleep_Day$SleepDay_New <- mdy_hms(Sleep_Day$SleepDay)
```

Three duplicates were found:

``` r
nrow(Sleep_Day[duplicated(Sleep_Day), ])
```

    ## [1] 3

Getting rid of duplicates:

``` r
Sleep_Day2 <- Sleep_Day %>% distinct()

nrow(Sleep_Day2)
```

    ## [1] 410

Merging tables Daily_Activity and Sleep_Day2:

``` r
df <- rename(Sleep_Day2,"ActivityDate_New"="SleepDay_New")

combined_data <- merge(df, Daily_Activity, by=c("Id","ActivityDate_New"))
```

We still have 24 respondents but 410 observations:

``` r
n_distinct(combined_data$Id)
```

    ## [1] 24

``` r
nrow(combined_data)
```

    ## [1] 410

By merging Daily Activity and Sleep data, the sample has been reduced
from 33 to 24 users. The sample is too small to draw any accurate
conclusions.

### Minutes Asleep

The recommended number of sleep hours for adults is between 7 to 9 hours
a day. 10 respondents (42%) sleep within the recommended range.

- Median: 433 minutes (7.22 hours)
- Mean: 419 minutes (7 hours)

``` r
ggplot(combined_data) +
  aes(x = "", y = TotalMinutesAsleep) +
  xlab(" ") +
  ylab("Minutes Asleep") +  
  ggtitle("Minutes Asleep Box Plot") +
  theme_minimal() +
  geom_boxplot(fill = "#0c4c8a") 
```

![](Bellabeat-Copy-From-Kaggle_files/figure-gfm/unnamed-chunk-28-1.png)<!-- -->
![unnamed-chunk-28-1](https://github.com/elgels/Bellabeat-Case-Study/assets/131495309/c4563523-c81f-4f61-bd58-b20bf7058cb5)

We found a positive correlation between TotalTimeInBed and
TotalMinutesAsleep. This makes sense, and in average the difference
between these two variables was 38.4 minutes.

### Fitbit Daily Usage

We assumed the following definition:

FitBit’s Daily Usage = Sedentary Minutes + Lightly Active Minutes +
Fairly Active Minutes + Very Active Minutes + Sleep Time

To calculate the average number of hours users worn the tracker in a
day, we run the following code:

``` r
Daily_Activity_AddedColumns_Usage <- combined_data %>% 
    group_by(Id, ActivityDate_New) %>% 
    summarise(UsageTotalTime=(TotalTimeInBed + SedentaryMinutes + LightlyActiveMinutes +  FairlyActiveMinutes + VeryActiveMinutes),  
    UsageHours=UsageTotalTime/60)
          
Daily_Activity_AddedColumns_Usage_t <- Daily_Activity_AddedColumns_Usage %>% 
    group_by(Id) %>% summarise(AveUsageTotalTimeperId=(mean(UsageTotalTime)/60))

Daily_Activity_AddedColumns_Usage_t2 <- Daily_Activity_AddedColumns_Usage_t %>% 
    mutate(Uselevel=if_else(AveUsageTotalTimeperId<24, "23 to less than 24 hours",
    (if_else(AveUsageTotalTimeperId<=24, "24 hours", "Over 24 hours to 26 hours"))))

ggplot(Daily_Activity_AddedColumns_Usage_t2, aes(x=Uselevel)) + geom_bar(fill="#0c4c8a") + 
    labs(x="", y="Number of Users", title="Repondents by Usage Level")
```

![](Bellabeat-Copy-From-Kaggle_files/figure-gfm/unnamed-chunk-29-1.png)<!-- -->
![unnamed-chunk-29-1](https://github.com/elgels/Bellabeat-Case-Study/assets/131495309/dce6181e-290a-418a-8234-ae3cd1fde050)

All respondents used their trackers between 23 and 26 hours per day. 17
respondents (71%) used the tracker between 23 and 24 hours a day.
Anything over 24 hours doesn’t make sense, it looks like a mistake was
made when collecting the data.

Trying to analyze people by dividing them in groups by usage level
wouldn’t work because the sample sizes are too small; and it would get
even worse if we get rid of the observations that have over 24 hours of
usage per day.

### Correlations

``` r
ggplot(data=Daily_Activity, aes(x=TotalSteps, y=SedentaryMinutes)) + geom_point() + geom_smooth(method=lm) +
  labs(x="Steps", y="Sedentary Minutes", title="Steps and Sedentary Minutes")
```

![](Bellabeat-Copy-From-Kaggle_files/figure-gfm/unnamed-chunk-30-1.png)<!-- -->
![unnamed-chunk-30-1](https://github.com/elgels/Bellabeat-Case-Study/assets/131495309/05024e5a-10c2-4910-b19c-e1c89634f940)

- Steps and Sedentary Minutes show a negative relationship. Although it
  seems obvious, it validates the notion that tracking steps leads to a
  healthier lifestyle.

``` r
ggplot(combined_data, aes(x=TotalMinutesAsleep, y=SedentaryMinutes)) + geom_point() + geom_smooth(method=lm) +
  labs(x="Minutes Asleep", y="Sedentary Minutes", title="Minutes Asleep vs. Sedentary Minutes")
```

![](Bellabeat-Copy-From-Kaggle_files/figure-gfm/unnamed-chunk-31-1.png)<!-- -->
![unnamed-chunk-31-1](https://github.com/elgels/Bellabeat-Case-Study/assets/131495309/395beaad-a08d-45ee-8b3b-26c4646901a5)

- Minutes Asleep and Sedentary Minutes show a negative relationship.
  Sedentary time doesn’t lead to a healthy lifestyle, and more sedentary
  time is related to less sleep.

``` r
ggplot(data=Daily_Activity, aes(x=TotalSteps, y=Calories)) + geom_point() + geom_smooth(method=lm) + 
    labs(x="Steps", y="Calories", title="Steps vs. Calories")
```

![](Bellabeat-Copy-From-Kaggle_files/figure-gfm/unnamed-chunk-32-1.png)<!-- -->
![unnamed-chunk-32-1](https://github.com/elgels/Bellabeat-Case-Study/assets/131495309/ba97b3f5-dfbc-40bf-a909-ed12e10a3d66)

- As expected, Steps and Calories show a positive relationship.

Doing more analysis we found that:

- As expected, both Steps and Calories tend to have a positive
  relationship with Minutes and Distance at all their intensity levels.

- No clear relationship was found between Minutes Asleep and Calories;
  and Minutes Asleep vs. Minutes and Distances.

## Hourly Data

Loading the hourly data:

``` r
hourlyCalories <- read_csv("hourlyCalories_merged.csv")

hourlyIntensities <- read_csv("hourlyIntensities_merged.csv")

hourlySteps <- read_csv("hourlySteps_merged.csv")
```

Looking at the structure of the tables:

``` r
str(hourlyCalories)
```

    ## spc_tbl_ [22,099 × 3] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
    ##  $ Id          : num [1:22099] 1.5e+09 1.5e+09 1.5e+09 1.5e+09 1.5e+09 ...
    ##  $ ActivityHour: chr [1:22099] "4/12/2016 12:00:00 AM" "4/12/2016 1:00:00 AM" "4/12/2016 2:00:00 AM" "4/12/2016 3:00:00 AM" ...
    ##  $ Calories    : num [1:22099] 81 61 59 47 48 48 48 47 68 141 ...
    ##  - attr(*, "spec")=
    ##   .. cols(
    ##   ..   Id = col_double(),
    ##   ..   ActivityHour = col_character(),
    ##   ..   Calories = col_double()
    ##   .. )
    ##  - attr(*, "problems")=<externalptr>

``` r
str(hourlyIntensities)
```

    ## spc_tbl_ [22,099 × 4] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
    ##  $ Id              : num [1:22099] 1.5e+09 1.5e+09 1.5e+09 1.5e+09 1.5e+09 ...
    ##  $ ActivityHour    : chr [1:22099] "4/12/2016 12:00:00 AM" "4/12/2016 1:00:00 AM" "4/12/2016 2:00:00 AM" "4/12/2016 3:00:00 AM" ...
    ##  $ TotalIntensity  : num [1:22099] 20 8 7 0 0 0 0 0 13 30 ...
    ##  $ AverageIntensity: num [1:22099] 0.333 0.133 0.117 0 0 ...
    ##  - attr(*, "spec")=
    ##   .. cols(
    ##   ..   Id = col_double(),
    ##   ..   ActivityHour = col_character(),
    ##   ..   TotalIntensity = col_double(),
    ##   ..   AverageIntensity = col_double()
    ##   .. )
    ##  - attr(*, "problems")=<externalptr>

``` r
str(hourlySteps)
```

    ## spc_tbl_ [22,099 × 3] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
    ##  $ Id          : num [1:22099] 1.5e+09 1.5e+09 1.5e+09 1.5e+09 1.5e+09 ...
    ##  $ ActivityHour: chr [1:22099] "4/12/2016 12:00:00 AM" "4/12/2016 1:00:00 AM" "4/12/2016 2:00:00 AM" "4/12/2016 3:00:00 AM" ...
    ##  $ StepTotal   : num [1:22099] 373 160 151 0 0 ...
    ##  - attr(*, "spec")=
    ##   .. cols(
    ##   ..   Id = col_double(),
    ##   ..   ActivityHour = col_character(),
    ##   ..   StepTotal = col_double()
    ##   .. )
    ##  - attr(*, "problems")=<externalptr>

Looking at data stats:

``` r
summary(hourlyCalories)
```

    ##        Id            ActivityHour          Calories     
    ##  Min.   :1.504e+09   Length:22099       Min.   : 42.00  
    ##  1st Qu.:2.320e+09   Class :character   1st Qu.: 63.00  
    ##  Median :4.445e+09   Mode  :character   Median : 83.00  
    ##  Mean   :4.848e+09                      Mean   : 97.39  
    ##  3rd Qu.:6.962e+09                      3rd Qu.:108.00  
    ##  Max.   :8.878e+09                      Max.   :948.00

``` r
summary(hourlyIntensities)
```

    ##        Id            ActivityHour       TotalIntensity   AverageIntensity
    ##  Min.   :1.504e+09   Length:22099       Min.   :  0.00   Min.   :0.0000  
    ##  1st Qu.:2.320e+09   Class :character   1st Qu.:  0.00   1st Qu.:0.0000  
    ##  Median :4.445e+09   Mode  :character   Median :  3.00   Median :0.0500  
    ##  Mean   :4.848e+09                      Mean   : 12.04   Mean   :0.2006  
    ##  3rd Qu.:6.962e+09                      3rd Qu.: 16.00   3rd Qu.:0.2667  
    ##  Max.   :8.878e+09                      Max.   :180.00   Max.   :3.0000

``` r
summary(hourlySteps)
```

    ##        Id            ActivityHour         StepTotal      
    ##  Min.   :1.504e+09   Length:22099       Min.   :    0.0  
    ##  1st Qu.:2.320e+09   Class :character   1st Qu.:    0.0  
    ##  Median :4.445e+09   Mode  :character   Median :   40.0  
    ##  Mean   :4.848e+09                      Mean   :  320.2  
    ##  3rd Qu.:6.962e+09                      3rd Qu.:  357.0  
    ##  Max.   :8.878e+09                      Max.   :10554.0

No duplicates were found:

``` r
nrow(hourlyCalories[duplicated(hourlyCalories), ])
```

    ## [1] 0

``` r
nrow(hourlyIntensities[duplicated(hourlyIntensities), ])
```

    ## [1] 0

``` r
nrow(hourlySteps [duplicated(hourlySteps ), ])
```

    ## [1] 0

Changing data type for variable ActivityHour (from character to date) by
creating a new column:

``` r
hourlyCalories$ActivityHour_New <- mdy_hms(hourlyCalories$ActivityHour)

hourlyIntensities$ActivityHour_New <- mdy_hms(hourlyIntensities$ActivityHour)

hourlySteps$ActivityHour_New <- mdy_hms(hourlySteps$ActivityHour)
```

Merging hourly tables (hourlyCalories, hourlyIntensities and
hourlySteps):

``` r
combined_hourly_temp <- merge(hourlyCalories,hourlyIntensities,by=c("Id","ActivityHour_New"))

combined_hourly <- merge(combined_hourly_temp, hourlySteps, by=c("Id","ActivityHour_New"))
```

Changing data type for variable ActivityHour to include hours of the
day:

``` r
    combined_hourly_h <- combined_hourly %>% 
    mutate(Hours=format(as.POSIXct(hourlySteps$ActivityHour_New), format = "%H"), dayofweek=weekdays(ActivityHour_New))
```

We found 33 unique users, the same number as the Daily_Activity data:

``` r
n_distinct(combined_hourly$Id)
```

    ## [1] 33

### Hourly Trends

To graph data by day of the week and by hour of the day:

``` r
combined_hourly_h1 <- combined_hourly_h %>% group_by(dayofweek, Hours) %>%
    summarise(avesteps=mean(StepTotal), avecal=mean(Calories), aveintensity=mean(AverageIntensity))
```

``` r
combined_hourly_h1$dayofweek <- ordered(combined_hourly_h1$dayofweek, levels=c("Monday", "Tuesday",
    "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"))

ggplot(data=combined_hourly_h1, aes(x=Hours, y=avesteps)) + labs(x="Hours of the Day", y="Average Steps", 
    title= "Average Steps by Day of the Week and Hours of the Day") + geom_bar(stat="identity", fill="#0c4c8a") +
    facet_wrap(~dayofweek) + theme(axis.text.x = element_text(angle = 45, size=5, color="#708090"))  
```

![](Bellabeat-Copy-From-Kaggle_files/figure-gfm/unnamed-chunk-42-1.png)<!-- -->
![unnamed-chunk-42-1](https://github.com/elgels/Bellabeat-Case-Study/assets/131495309/3ed92f98-c6a3-4e37-b810-e93fd62ded39)

- From Monday through Friday steps peak between 5pm to 7pm.

- On Tuesdays and Thursdays steps increase around launch time as well.

- On Saturdays there is a peak between 12pm and 2pm.

- Respondents seem to follow a typical working schedule (9am to 5pm).

- They tend to increase their step count right after work and around
  launch time.

``` r
ggplot(data=combined_hourly_h1, aes(x=Hours, y=avecal)) + labs(x="Hours of the Day", y="Calories",
  title= "Average Calories by Day of the Week and Hours of the Day")  +                                                         
  geom_bar(stat="identity", fill="#0c4c8a") + facet_wrap(~dayofweek) +
  theme(axis.text.x = element_text(angle = 45, size=5, color="#708090"))  
```

![](Bellabeat-Copy-From-Kaggle_files/figure-gfm/unnamed-chunk-43-1.png)<!-- -->
![unnamed-chunk-43-1](https://github.com/elgels/Bellabeat-Case-Study/assets/131495309/d716d356-f330-46b9-b27b-53e87940e872)

Average Calories burned follow the same hourly pattern as Steps.

``` r
ggplot(data=combined_hourly_h1, aes(x=Hours, y=aveintensity)) + labs(x="Hours of the Day", y="Average Intensity",
  title= "Average Intensity by Day of the Week and Hours of the Day")  +  
  geom_bar(stat="identity", fill="#0c4c8a") + facet_wrap(~dayofweek) +
  theme(axis.text.x = element_text(angle = 45, size=5, color="#708090"))  
```

![](Bellabeat-Copy-From-Kaggle_files/figure-gfm/unnamed-chunk-44-1.png)<!-- -->
![unnamed-chunk-44-1](https://github.com/elgels/Bellabeat-Case-Study/assets/131495309/132e3250-6a99-45dc-9110-6f7a6efcaceb)

From the data dictionary document
([link](https://www.fitabase.com/media/1930/fitabasedatadictionary102320.pdf)),
Intensity values are defined as: 0 = Sedentary, 1 = Light, 2 = Moderate
and 3 = Very Active. We assume these Intensity values correspond to the
activity types defined for Minutes and Distance.

Average Intensity follows the same hourly pattern as Steps and Calories.

### Correlations

``` r
ggplot(data=combined_hourly, aes(x=StepTotal, y=Calories)) + geom_point() + geom_smooth(method=lm) +
  labs(x="Steps", y="Calories", title="Steps vs. Calories")
```

![](Bellabeat-Copy-From-Kaggle_files/figure-gfm/unnamed-chunk-45-1.png)<!-- -->
![unnamed-chunk-45-1](https://github.com/elgels/Bellabeat-Case-Study/assets/131495309/df67b312-de9c-4184-a076-f5acb03081cc)

- Positive relationship found between Steps taken and Calories burned,
  same result as in the daily data.

``` r
ggplot(data=combined_hourly, aes(x=Calories, y=AverageIntensity)) + geom_point() + geom_smooth(method=lm) +
  labs(x="Calories", y="Average Intensity", title="Calories vs. Average Intensity")
```

![](Bellabeat-Copy-From-Kaggle_files/figure-gfm/unnamed-chunk-46-1.png)<!-- -->
![unnamed-chunk-46-1](https://github.com/elgels/Bellabeat-Case-Study/assets/131495309/fd23cf53-e4ab-4fa4-ae6c-ca986b6edb2d)

- Average Intensity and Calories burned show to have a positive
  relationship.

``` r
ggplot(data=combined_hourly, aes(x=StepTotal, y=AverageIntensity)) + geom_point() + geom_smooth(method=lm) +
  labs(x="Steps", y="Average Intensity", title="Steps vs. Average Intensity")
```

![](Bellabeat-Copy-From-Kaggle_files/figure-gfm/unnamed-chunk-47-1.png)<!-- -->
![unnamed-chunk-47-1](https://github.com/elgels/Bellabeat-Case-Study/assets/131495309/7958bbe0-13bd-4fb9-8613-fb9b8ec981fa)

- The higher the number of Steps taken, the higher the average Intensity
  value.

## Weight Data

Loading the weight information file:

``` r
WeightInfo <- read_csv("weightLogInfo_merged.csv")
```

    ## Rows: 67 Columns: 8
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): Date
    ## dbl (6): Id, WeightKg, WeightPounds, Fat, BMI, LogId
    ## lgl (1): IsManualReport
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Looking at the structure of the data:

``` r
str(WeightInfo)
```

    ## spc_tbl_ [67 × 8] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
    ##  $ Id            : num [1:67] 1.50e+09 1.50e+09 1.93e+09 2.87e+09 2.87e+09 ...
    ##  $ Date          : chr [1:67] "5/2/2016 11:59:59 PM" "5/3/2016 11:59:59 PM" "4/13/2016 1:08:52 AM" "4/21/2016 11:59:59 PM" ...
    ##  $ WeightKg      : num [1:67] 52.6 52.6 133.5 56.7 57.3 ...
    ##  $ WeightPounds  : num [1:67] 116 116 294 125 126 ...
    ##  $ Fat           : num [1:67] 22 NA NA NA NA 25 NA NA NA NA ...
    ##  $ BMI           : num [1:67] 22.6 22.6 47.5 21.5 21.7 ...
    ##  $ IsManualReport: logi [1:67] TRUE TRUE FALSE TRUE TRUE TRUE ...
    ##  $ LogId         : num [1:67] 1.46e+12 1.46e+12 1.46e+12 1.46e+12 1.46e+12 ...
    ##  - attr(*, "spec")=
    ##   .. cols(
    ##   ..   Id = col_double(),
    ##   ..   Date = col_character(),
    ##   ..   WeightKg = col_double(),
    ##   ..   WeightPounds = col_double(),
    ##   ..   Fat = col_double(),
    ##   ..   BMI = col_double(),
    ##   ..   IsManualReport = col_logical(),
    ##   ..   LogId = col_double()
    ##   .. )
    ##  - attr(*, "problems")=<externalptr>

No duplicates were found:

``` r
nrow(WeightInfo[duplicated(WeightInfo), ])
```

    ## [1] 0

Changing data type for variable Date (from character to date) by
creating a new column:

``` r
WeightInfo$Date_New <- mdy_hms(WeightInfo$Date)
```

We only have 8 respondents, making the sample size too small to draw any
accurate conclusions.

``` r
n_distinct(WeightInfo$Id)
```

    ## [1] 8

Looking at data stats:

``` r
Weight_Sum <- WeightInfo %>% group_by(Id) %>% 
  summarise(mean_WeightPounds=mean(WeightPounds), mean_BMI=mean(BMI))
  
summary(Weight_Sum)
```

    ##        Id            mean_WeightPounds    mean_BMI    
    ##  Min.   :1.504e+09   Min.   :116.0     Min.   :21.57  
    ##  1st Qu.:2.637e+09   1st Qu.:133.2     1st Qu.:23.68  
    ##  Median :4.439e+09   Median :156.5     Median :26.35  
    ##  Mean   :4.575e+09   Mean   :171.5     Mean   :27.99  
    ##  3rd Qu.:5.923e+09   3rd Qu.:190.8     3rd Qu.:27.56  
    ##  Max.   :8.878e+09   Max.   :294.3     Max.   :47.54

``` r
Weight_Sum <- transform(Weight_Sum, Category=if_else(mean_BMI>18.5 & mean_BMI<24.9,
    "Healthy Weight",(if_else(mean_BMI>25 & mean_BMI<29.9,"Overweight","Obese"))))

ggplot(Weight_Sum, aes(x=" ", y=" ", fill=Category)) + geom_bar(stat="identity", width=1) + 
    coord_polar(theta="y") + labs(x = " ", y = " ", title = "Users Average Weight") + 
    geom_text(stat="count", aes(y=after_stat(..count..), label=after_stat(scales::percent(..count../sum(..count..),1))), 
    position = position_stack(vjust = 0.4), size = 3, check_overlap= TRUE) +
    theme(legend.title=element_blank()) + theme_void()
```

![](Bellabeat-Copy-From-Kaggle_files/figure-gfm/unnamed-chunk-54-1.png)<!-- -->
![unnamed-chunk-54-1](https://github.com/elgels/Bellabeat-Case-Study/assets/131495309/40b4ac5e-8d23-46be-9c45-dc1092515f06)

5 (63%) users are overweight or obese. But this sample is too small to
conclude anything regarding the population.

# CONCLUSIONS

## Data Limitations

- Lack of demographic information is a challenge because the sample
  could be biased. This is especially important when considering that
  Bellabeat targets women.

- Sample sizes are small, we start with 33 users but then this number
  decreases to 24 when we include sleep data. For weight we only have
  information for 8 users. For this reason, we can’t draw solid
  conclusions from this data.

- Data is not recent (it was collected from April through May 2016), 7
  years old as of the time this document was written.

- We found discrepancies in the data, for example: 1) Sedentary minutes
  seemed to have been overestimated; and 2) Some users recorded wearing
  the FitBit for more than 24 hours a day. These inaccuracies raise
  questions about the validity of the data.

- FitBit and the Bellabeat watch have different features. They both have
  an app where people can track their stats, but the FitBit is a fitness
  band and a smartwatch while the Bellabeat tracker looks like a
  traditional watch. The Bellabeat customer seems to be more specific on
  the type of design she likes: a timeless classic watch with the hidden
  technology of a FitBit.

- The FiBit tracking technology is proprietary and we don’t know their
  methodology to calculate activity intensities and aggregated values
  (e.g. minutes to hours). We assume Bellabeat uses a similar tracking
  technology.

## Recommendations

- The users in this sample seem to follow typical behaviors regarding
  Steps, Calories burned, Sleep and daily activity measured in time and
  distance. According to this sample, users seem to spend most of their
  time being sedentary, the steps they take are way below the
  recommended amount a day (10,000 steps) and most of the their distance
  is related to light or moderate activities.

- The people in this group appear to be typical, but they see an
  opportunity for improving their overall health. The marketing message
  should emphasize that trackers play an important role in achieving
  healthy goals: Lose weight, improve sleep, and reduce stress.

- Since the tracker appeals to people looking for a healthy lifestyle,
  the marketing message could include calls to action to start walking
  more, loose more calories and get better sleep. It’d be useful to
  remind users that trackers can send reminders during the day to help
  them achieve these goals.

- We’d like to have more reliable data on weight and sleep quality
  because these are key factors influencing why customers wear FitBits.

- We think users would like to see stress indicators and mindfulness
  features in the app. Ideally, we’d like to conclude that the more
  steps and exercise lead to a reduction in heart rate, and therefore to
  less stress. However, the available heart rate data is reported in
  seconds. We would need to have a methodology to aggregate the heart
  rate values to minutes or hours to be able to compare it to the other
  variables.

- Per the information provided in this case study, we know that
  Bellabeat sells through their own e-commerce store focusing mainly on
  digital marketing. Better insights from consumers’ behaviors and
  motivations would allow the digital marketing team to increase traffic
  and conversions using different channels such as:

  - Pay-per-click: Finding keywords that customers are searching for on
    Google Search. Getting to bid on more specific and long-tail
    keywords to improve marketing costs.

  - Social Media: Adding the right content to Bellabeat’s Facebook page
    and useful videos to Youtube, would inform customers that Bellabeat
    is all about healthy living, and an authority on smart devices and
    tracking technology.

  - Display Ads: The Google Display Network would be a great way to
    advertise on websites that have the right content and traffic.
    Across the web there are plenty of opportunities to reach potential
    customers who are already reading about healthy living and looking
    for interesting content.
